### ISSUE TITLE
[EPIC] WebSockets

### ISSUE THREAD

**Issue by tzdybal** [rollkit/go-execution-abci#18]
Experiments with Ignite CLI shows multiple issues with Optimint-Tendermint compatibility. This is a tracks progress of discovering and fixing issues.

- [x] rollkit/rollkit#436 
- [x] rollkit/rollkit#241 - especially `NodeInfo` needs to be set
- [ ] rollkit/go-execution-abci#17 
- [ ] rollkit/rollkit#449
- [ ] https://github.com/rollkit/rollkit/issues/465
