### ISSUE TITLE
Integration tests for cosmos-sdk App & CosmWasm Rollup

### ISSUE THREAD

**Issue by Bidon15** [rollkit/go-execution-abci#42]
Introduction 🧐 
---

~~As @smuu will be taking charge of https://github.com/celestiaorg/devops/issues/129, 
this is a breakdown of initial work that we need to do.~~

Ideas to start with 📝 
---

It will be beneficial if we can check that a running rollup can have the same functionality as the L1 version of it, such as: 

```[tasklist]
### Tasks
- [ ] Simple TXs (send, multi-send)
- [ ] Staking
- [ ] Queries IP:Ports of the node (grpc/rpc/rest/etc.)
```

Implementation
---

~~We can use this https://github.com/celestiaorg/devops/issues/291 when the first iteration of the framework comes out~~
We should fork https://github.com/cosmos/cosmos-sdk/tree/main/systemtests and make it a standard rollup framework:

- [ ] Run DA + Node

Then we can perform tests on the node.

- [ ] Ideally this epic should cover tests that are executed on every PR 
- [ ] Tests should be short-lived 
- [ ] using local-devnet docker image makes sense as a base assumption that DA is operable

**Comment by julienrbrt** [comment]
I can extend https://github.com/rollkit/go-execution-abci/pull/81 eventually to make a tx and query it

**Comment by julienrbrt** [comment]
Partly implemented in https://github.com/rollkit/go-execution-abci/pull/87.
We can either wait for cosmwasm tests until we fork system tests or split the current workflow and init a cosmwasm chain.

**Comment by tac0turtle** [comment]
there is a simple set of system test helpers in rollkit, are we able to use anything there?

**Comment by julienrbrt** [comment]
> [@julienrbrt](https://github.com/julienrbrt) can we close this one? or are we still missing cw? maybe we dont need cw as when we have sdk+ibc cw should work as well

we do not have CW. we have sdk+ibc and just sdk

**Comment by tac0turtle** [comment]
will close as completed
